### ISSUE TITLE
Downloading Files

### ISSUE THREAD

**Issue by Nosfir** [0blio/Caesar#13]
So after messing around with this for a while, I can't seem to download anyfiles with the extensions "rar, zip, js" etc..

**Comment by 0blio** [comment]
Do you receive any error?
You should try to grant permissions to the Caesar's install folder by using:
`chmod -R 777 <caesar_install_folder>`

**Comment by 0blio** [comment]
Any updates about this?

**Comment by ChronoHELP** [comment]
> Any updates about this?

Yeah (I am nosfir just lost the account and don't care enough to get it back) 
Everything worked out!

**Comment by 0blio** [comment]
Fixed.
